# Makefile
# generated on <%= Time.now %>
# by <%= @author %>
# With the Condom lib (version <%= Condom::VERSION %>)
# See http://github.com/vivien/condom

FINAL_FILENAME=<%= @filename %>
FILENAME=main
VIEWER?=xdg-open
RUBBER=$(shell which rubber 2>/dev/null)

all: $(FINAL_FILENAME).pdf

$(FINAL_FILENAME).pdf: $(FILENAME).tex
ifeq ($(RUBBER),)
	@pdflatex $(FILENAME).tex
	@pdflatex $(FILENAME).tex
	@echo -e "\nYou should install the rubber package ;)"
else
	@$(RUBBER) -d $(FILENAME).tex
endif
ifneq ($(FILENAME),$(FINAL_FILENAME))
	@mv $(FILENAME).pdf $(FINAL_FILENAME).pdf
endif

view: $(FINAL_FILENAME).pdf
	@$(VIEWER) $(FINAL_FILENAME).pdf

clean:
	@echo "cleaning..."
	@rm -f *.aux *.log *.out *.toc *.lol<% if @listings %> *.lof<% end %><% if @document_class == "beamer" %> *.nav *.snm *.vrb<% end %><% unless @document_class == "letter" %>
	@rm -f inc/*.aux<% end %>
	@rm -f $(FINAL_FILENAME).tar

distclean: clean
	@rm -f $(FINAL_FILENAME).pdf
	@rm -f $(FINAL_FILENAME)-{src,dist}.tar

archive: all clean
	@tar -cf $(FINAL_FILENAME)-src.tar *
	@echo "archived in $(FINAL_FILENAME)-src.tar"

dist: all
	@tar -cf $(FINAL_FILENAME)-dist.tar $(FINAL_FILENAME).pdf<% if @listings %> src/<% end %>
	@echo "archived in $(FINAL_FILENAME)-dist.tar"
