# Makefile
# generated on <%= Time.now %>
# by <%= @author %>
# With the Condom lib (version <%= Condom::VERSION %>)
# See http://github.com/vivien/condom

FINAL_FILENAME=<%= @filename %>
FILENAME=main
VIEWER=xdg-open
RUBBER=$(shell which rubber)

all: $(FILENAME).tex
ifeq ($(RUBBER),)
	@pdflatex $(FILENAME).tex
	@pdflatex $(FILENAME).tex
	@echo -e "\nYou should install the rubber package ;)"
else
	@$(RUBBER) -d $(FILENAME).tex
endif
ifneq ($(FILENAME),$(FINAL_FILENAME))
	@mv $(FILENAME).pdf $(FINAL_FILENAME).pdf
endif

view: all
	@$(VIEWER) $(FINAL_FILENAME).pdf

clean:
	@echo "cleaning..."
	@rm -f *.aux *.log *.out *.toc *.lol<% if @listings %> *.lof<% end %><% if @document_class == "beamer" %> *.nav *.snm<% end %><% unless @document_class == "letter" %>
	@rm -f inc/*.aux<% end %>
	@rm -f $(FINAL_FILENAME).tar

archive: all clean
	@tar -cf $(FINAL_FILENAME).tar *
	@echo "archived in $(FINAL_FILENAME).tar"
